### PR TITLE
Debugging

### PR DESCRIPTION
**Pull request by gorgorgordon**
Improvements as below:

Good question. 

1. First of all, if you use DevTools, to open your index.html, you should see error "unexpected end of input (index.js line 52). 

Reason is poor indentation of code block, the }); at line 51 corresponds to addEventListener at line 7, and you have not close the for loop at line 5.

You need to add one more } to close the for loop.

2. After the first fix, console log blank at img click, because of line 47:

  default: console.log(buttonByClass);

where buttonByClass is at line 9:

var buttonByClass = this.innerHTML;

Here, don't use this.innerHTML, use event.target.matches(".classname") where classname is the classification added in class of the img element.

Further improvement opportunities :

Lastly, new Audio is asynchronous, you should load them before the user are allowed to interact (add a loading), and in the switch in click event listener, you use the play() method only.

### CODE REVIEW

**Comment by El-lobo-cimarron** [comment]
Thank you for your response! I updated file, but it still doesn't make any sound

**Comment by gorgorgordon** [comment]
I see that your updated version is using this.matches(".bn")

You will need to use matches on event.target where event is mouseClickEvent
function (event) {
}

and the argument to matches() is not ".bn", it should be each individual emotion one by one (let go of the switch).

See the code snippet in my pull request above. You can commit it to master branch to see.

**Comment by El-lobo-cimarron** [comment]
Thank you for your time! I see, I didn't study this concepts yet. So, I copied your code, but still not working and it says that there is some problem with '{' in index.js:14

**Comment by gorgorgordon** [comment]
Oh I am missing a ) to close if condition in all if conditions, my bad.

**Comment by El-lobo-cimarron** [comment]
OMG IT WORKS!!! Thank you so much!!! How can I mention you in this project?

**Comment by gorgorgordon** [comment]
Don't worry about mentioning. It is something very simple.

I only hope I have more time so I can demonstrate event delegation (so you don't need to add event listener one by one) and how to use onload of Audio (It works now only because the audio file is of small size).

Maybe another chance next time.

Or, if you don't mind, I use your project to record a tutorial video and upload to YouTube so you can how to further improve it.

**Pull request closed without merging**
